=begin
#My Data My Consent - Developer API

#Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.

The version of the OpenAPI document: v1
Contact: support@mydatamyconsent.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

require 'date'
require 'time'

module OpenapiClient
  class OrganizationStatus
    ORGANIZATION_CREATED = "OrganizationCreated".freeze
    CONTACT_DETAILS_UPDATED = "ContactDetailsUpdated".freeze
    OVERVIEW_UPDATED = "OverviewUpdated".freeze
    ADDRESS_UPDATED = "AddressUpdated".freeze
    BANK_ACCOUNTS_UPDATED = "BankAccountsUpdated".freeze
    SIGN_UP_COMPLETED = "SignUpCompleted".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = OrganizationStatus.constants.select { |c| OrganizationStatus::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #OrganizationStatus" if constantValues.empty?
      value
    end
  end
end
