=begin
#My Data My Consent - Developer API

#Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.

The version of the OpenAPI document: v1
Contact: support@mydatamyconsent.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/application_user'
require 'openapi_client/models/bank_account_type'
require 'openapi_client/models/category_icon_font_family'
require 'openapi_client/models/country'
require 'openapi_client/models/country_state'
require 'openapi_client/models/data_consent'
require 'openapi_client/models/data_consent_details_dto'
require 'openapi_client/models/data_consent_identifier'
require 'openapi_client/models/data_consent_request_model'
require 'openapi_client/models/data_consent_requested_account_dto'
require 'openapi_client/models/data_consent_requested_document'
require 'openapi_client/models/data_consent_requested_document_dto'
require 'openapi_client/models/data_consent_requested_fa_dto'
require 'openapi_client/models/data_consent_requested_financial_account'
require 'openapi_client/models/data_consent_requester_dto'
require 'openapi_client/models/data_consent_rfa_filter'
require 'openapi_client/models/data_consent_rfa_filter_dto'
require 'openapi_client/models/data_consent_status'
require 'openapi_client/models/data_fetch_frequency_unit'
require 'openapi_client/models/data_fetch_type'
require 'openapi_client/models/data_life_unit'
require 'openapi_client/models/data_processing_agreement'
require 'openapi_client/models/data_processing_agreement_paginated_list'
require 'openapi_client/models/data_protection_officer'
require 'openapi_client/models/data_provider'
require 'openapi_client/models/data_provider_paginated_list'
require 'openapi_client/models/document_issue_request'
require 'openapi_client/models/document_provider_category'
require 'openapi_client/models/file_type'
require 'openapi_client/models/filter_type'
require 'openapi_client/models/financial_account_types'
require 'openapi_client/models/gender'
require 'openapi_client/models/identification_strategy'
require 'openapi_client/models/identifier'
require 'openapi_client/models/identifier_string_key_value_pair'
require 'openapi_client/models/identity_claim'
require 'openapi_client/models/json_schema'
require 'openapi_client/models/operator'
require 'openapi_client/models/organization'
require 'openapi_client/models/organization_address'
require 'openapi_client/models/organization_address_type'
require 'openapi_client/models/organization_category'
require 'openapi_client/models/organization_financial_account'
require 'openapi_client/models/organization_kyo_document'
require 'openapi_client/models/organization_meta_data'
require 'openapi_client/models/organization_status'
require 'openapi_client/models/organization_type'
require 'openapi_client/models/problem_details'
require 'openapi_client/models/proof_document_type'
require 'openapi_client/models/push_uri_request'
require 'openapi_client/models/push_uri_response'
require 'openapi_client/models/receiver'
require 'openapi_client/models/receiver_type'
require 'openapi_client/models/refresh_token'
require 'openapi_client/models/rejection'
require 'openapi_client/models/suggested_account_dto'
require 'openapi_client/models/theme'
require 'openapi_client/models/uri_details'

# APIs
require 'openapi_client/api/data_consent_requests_api'
require 'openapi_client/api/data_consents_api'
require 'openapi_client/api/data_processing_agreements_api'
require 'openapi_client/api/data_provider_discovery_api'
require 'openapi_client/api/digi_locker_compat_issuer_api'
require 'openapi_client/api/documents_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
