=begin
#My Data My Consent - Developer API

#Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.

The version of the OpenAPI document: 1.0
Contact: support@mydatamyconsent.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.0

=end

require 'date'
require 'time'

module MyDataMyConsent
  class TermDepositInformation
    attr_accessor :deposit_type

    attr_accessor :description

    attr_accessor :currency_code

    attr_accessor :principal_amount

    attr_accessor :interest_rate

    attr_accessor :interest_payout

    attr_accessor :interest_computation

    attr_accessor :compounding_frequency

    attr_accessor :interest_periodic_payout_amount

    attr_accessor :interest_on_maturity

    attr_accessor :deposit_opening_date

    attr_accessor :maturity_date

    attr_accessor :maturity_amount

    attr_accessor :tenure_days

    attr_accessor :tenure_months

    attr_accessor :tenure_years

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'deposit_type' => :'deposit_type',
        :'description' => :'description',
        :'currency_code' => :'currency_code',
        :'principal_amount' => :'principal_amount',
        :'interest_rate' => :'interest_rate',
        :'interest_payout' => :'interest_payout',
        :'interest_computation' => :'interest_computation',
        :'compounding_frequency' => :'compounding_frequency',
        :'interest_periodic_payout_amount' => :'interest_periodic_payout_amount',
        :'interest_on_maturity' => :'interest_on_maturity',
        :'deposit_opening_date' => :'deposit_opening_date',
        :'maturity_date' => :'maturity_date',
        :'maturity_amount' => :'maturity_amount',
        :'tenure_days' => :'tenure_days',
        :'tenure_months' => :'tenure_months',
        :'tenure_years' => :'tenure_years'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'deposit_type' => :'TermDepositAccountType',
        :'description' => :'String',
        :'currency_code' => :'String',
        :'principal_amount' => :'Float',
        :'interest_rate' => :'Float',
        :'interest_payout' => :'TermDepositInterestPayoutType',
        :'interest_computation' => :'TermDepositInterestComputation',
        :'compounding_frequency' => :'TermDepositCompoundingFrequency',
        :'interest_periodic_payout_amount' => :'Float',
        :'interest_on_maturity' => :'Float',
        :'deposit_opening_date' => :'Time',
        :'maturity_date' => :'Time',
        :'maturity_amount' => :'Float',
        :'tenure_days' => :'Integer',
        :'tenure_months' => :'Integer',
        :'tenure_years' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `MyDataMyConsent::TermDepositInformation` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `MyDataMyConsent::TermDepositInformation`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'deposit_type')
        self.deposit_type = attributes[:'deposit_type']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'currency_code')
        self.currency_code = attributes[:'currency_code']
      end

      if attributes.key?(:'principal_amount')
        self.principal_amount = attributes[:'principal_amount']
      end

      if attributes.key?(:'interest_rate')
        self.interest_rate = attributes[:'interest_rate']
      end

      if attributes.key?(:'interest_payout')
        self.interest_payout = attributes[:'interest_payout']
      end

      if attributes.key?(:'interest_computation')
        self.interest_computation = attributes[:'interest_computation']
      end

      if attributes.key?(:'compounding_frequency')
        self.compounding_frequency = attributes[:'compounding_frequency']
      end

      if attributes.key?(:'interest_periodic_payout_amount')
        self.interest_periodic_payout_amount = attributes[:'interest_periodic_payout_amount']
      end

      if attributes.key?(:'interest_on_maturity')
        self.interest_on_maturity = attributes[:'interest_on_maturity']
      end

      if attributes.key?(:'deposit_opening_date')
        self.deposit_opening_date = attributes[:'deposit_opening_date']
      end

      if attributes.key?(:'maturity_date')
        self.maturity_date = attributes[:'maturity_date']
      end

      if attributes.key?(:'maturity_amount')
        self.maturity_amount = attributes[:'maturity_amount']
      end

      if attributes.key?(:'tenure_days')
        self.tenure_days = attributes[:'tenure_days']
      end

      if attributes.key?(:'tenure_months')
        self.tenure_months = attributes[:'tenure_months']
      end

      if attributes.key?(:'tenure_years')
        self.tenure_years = attributes[:'tenure_years']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @deposit_type.nil?
        invalid_properties.push('invalid value for "deposit_type", deposit_type cannot be nil.')
      end

      if @description.nil?
        invalid_properties.push('invalid value for "description", description cannot be nil.')
      end

      if @currency_code.nil?
        invalid_properties.push('invalid value for "currency_code", currency_code cannot be nil.')
      end

      if @principal_amount.nil?
        invalid_properties.push('invalid value for "principal_amount", principal_amount cannot be nil.')
      end

      if @interest_rate.nil?
        invalid_properties.push('invalid value for "interest_rate", interest_rate cannot be nil.')
      end

      if @interest_payout.nil?
        invalid_properties.push('invalid value for "interest_payout", interest_payout cannot be nil.')
      end

      if @interest_computation.nil?
        invalid_properties.push('invalid value for "interest_computation", interest_computation cannot be nil.')
      end

      if @compounding_frequency.nil?
        invalid_properties.push('invalid value for "compounding_frequency", compounding_frequency cannot be nil.')
      end

      if @interest_periodic_payout_amount.nil?
        invalid_properties.push('invalid value for "interest_periodic_payout_amount", interest_periodic_payout_amount cannot be nil.')
      end

      if @interest_on_maturity.nil?
        invalid_properties.push('invalid value for "interest_on_maturity", interest_on_maturity cannot be nil.')
      end

      if @deposit_opening_date.nil?
        invalid_properties.push('invalid value for "deposit_opening_date", deposit_opening_date cannot be nil.')
      end

      if @maturity_date.nil?
        invalid_properties.push('invalid value for "maturity_date", maturity_date cannot be nil.')
      end

      if @maturity_amount.nil?
        invalid_properties.push('invalid value for "maturity_amount", maturity_amount cannot be nil.')
      end

      if @tenure_days.nil?
        invalid_properties.push('invalid value for "tenure_days", tenure_days cannot be nil.')
      end

      if @tenure_months.nil?
        invalid_properties.push('invalid value for "tenure_months", tenure_months cannot be nil.')
      end

      if @tenure_years.nil?
        invalid_properties.push('invalid value for "tenure_years", tenure_years cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @deposit_type.nil?
      return false if @description.nil?
      return false if @currency_code.nil?
      return false if @principal_amount.nil?
      return false if @interest_rate.nil?
      return false if @interest_payout.nil?
      return false if @interest_computation.nil?
      return false if @compounding_frequency.nil?
      return false if @interest_periodic_payout_amount.nil?
      return false if @interest_on_maturity.nil?
      return false if @deposit_opening_date.nil?
      return false if @maturity_date.nil?
      return false if @maturity_amount.nil?
      return false if @tenure_days.nil?
      return false if @tenure_months.nil?
      return false if @tenure_years.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          deposit_type == o.deposit_type &&
          description == o.description &&
          currency_code == o.currency_code &&
          principal_amount == o.principal_amount &&
          interest_rate == o.interest_rate &&
          interest_payout == o.interest_payout &&
          interest_computation == o.interest_computation &&
          compounding_frequency == o.compounding_frequency &&
          interest_periodic_payout_amount == o.interest_periodic_payout_amount &&
          interest_on_maturity == o.interest_on_maturity &&
          deposit_opening_date == o.deposit_opening_date &&
          maturity_date == o.maturity_date &&
          maturity_amount == o.maturity_amount &&
          tenure_days == o.tenure_days &&
          tenure_months == o.tenure_months &&
          tenure_years == o.tenure_years
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [deposit_type, description, currency_code, principal_amount, interest_rate, interest_payout, interest_computation, compounding_frequency, interest_periodic_payout_amount, interest_on_maturity, deposit_opening_date, maturity_date, maturity_amount, tenure_days, tenure_months, tenure_years].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = MyDataMyConsent.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
